In [1]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV, train_test_split

import pandas as pd
import numpy as np 
import seaborn  as sns
import matplotlib.pyplot as plt

%matplotlib inline 
sns.set('notebook')

import warnings

warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import metrics
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler

In [2]:
# скачаємо файл
url = 'https://raw.githubusercontent.com/Illia061/StepProject/main/IKEA_SA_Furniture_Web_Scrapings_sss.csv'

df_ikea = pd.read_csv(url)

In [3]:
'''Step1 EDA'''
#Step 1: EDA - shape, head, tail, sample, info
'''
Аналізуємо набір данних магазину IKEA
На першому кроці аналізуємо та описуємо набір
Він має 3694 рядки та 14 стовпців
'''
df_ikea.shape

(3694, 14)

In [14]:
df_ikea.head()

,Unnamed: 0,item_id,name,category,price,old_price,sellable_online,link,other_colors,short_description,designer,depth,height,width
0,0,90420332,FREKVENS,Bar furniture,265.0,No old price,True,https://www.ikea.com/sa/en/p/frekvens-bar-tabl...,No,"Bar table, in/outdoor, 51x51 cm",Nicholai Wiig Hansen,NaN,99.0,51.0
1,1,368814,NORDVIKEN,Bar furniture,995.0,No old price,False,https://www.ikea.com/sa/en/p/nordviken-bar-tab...,No,"Bar table, 140x80 cm",Francis Cayouette,NaN,105.0,80.0
2,2,9333523,NORDVIKEN / NORDVIKEN,Bar furniture,2095.0,No old price,False,https://www.ikea.com/sa/en/p/nordviken-nordvik...,No,Bar table and 4 bar stools,Francis Cayouette,NaN,NaN,NaN
3,3,80155205,STIG,Bar furniture,69.0,No old price,True,https://www.ikea.com/sa/en/p/stig-bar-stool-wi...,Yes,"Bar stool with backrest, 74 cm",Henrik Preutz,50.0,100.0,60.0
4,4,30180504,NORBERG,Bar furniture,225.0,No old price,True,https://www.ikea.com/sa/en/p/norberg-wall-moun...,No,"Wall-mounted drop-leaf table, ...",Marcus Arvonen,60.0,43.0,74.0

In [7]:
df_ikea.tail()

,Unnamed: 0,item_id,name,category,price,old_price,sellable_online,link,other_colors,short_description,designer,depth,height,width
3689,3689,99157902,ELVARLI,Wardrobes,750.0,SR 820,True,https://www.ikea.com/sa/en/p/elvarli-1-section...,No,"1 section, 92x51x222-350 cm",Ehlén Johansson,50.0,NaN,91.0
3690,3690,9158152,ELVARLI,Wardrobes,1572.0,"SR 1,755",True,https://www.ikea.com/sa/en/p/elvarli-2-section...,No,"2 sections, 135x51x222-350 cm",Ehlén Johansson,50.0,NaN,135.0
3691,3691,59157541,ELVARLI,Wardrobes,924.0,"SR 1,050",True,https://www.ikea.com/sa/en/p/elvarli-2-section...,No,"2 sections, 175x51x222-350 cm",Ehlén Johansson,50.0,NaN,175.0
3692,3692,89157573,ELVARLI,Wardrobes,2745.0,"SR 3,130",True,https://www.ikea.com/sa/en/p/elvarli-3-section...,No,"3 sections, 178x51x222-350 cm",Ehlén Johansson,50.0,NaN,178.0
3693,3693,69157376,ELVARLI,Wardrobes,1231.0,"SR 1,535",True,https://www.ikea.com/sa/en/p/elvarli-2-section...,No,"2 sections, 175x51x222-350 cm",Ehlén Johansson,50.0,NaN,175.0

In [9]:
df_ikea.sample(5)

,Unnamed: 0,item_id,name,category,price,old_price,sellable_online,link,other_colors,short_description,designer,depth,height,width
578,578,60333850,BROR,Bookcases & shelving units,495.0,No old price,True,https://www.ikea.com/sa/en/p/bror-trolley-blac...,No,"Trolley, 85x55 cm",IKEA of Sweden,NaN,88.0,55.0
768,768,90265246,HISHULT,Bookcases & shelving units,35.0,No old price,True,https://www.ikea.com/sa/en/p/hishult-handle-po...,No,"Handle, 140 mm",K Hagberg/M Hagberg,37.0,NaN,12.0
3214,3214,69221320,EKEDALEN / HENRIKSDAL,Tables & desks,4565.0,No old price,True,https://www.ikea.com/sa/en/p/ekedalen-henriksd...,No,"Table and 6 chairs, 180/240 cm",Karl Malmvall/Ehlén Johansson,NaN,NaN,NaN
720,720,10353765,KLIMPEN,Bookcases & shelving units,345.0,No old price,True,https://www.ikea.com/sa/en/p/klimpen-table-leg...,Yes,"Table leg with storage, 58x70 cm",Tina Christensen,33.0,70.0,58.0
466,466,19266603,BESTÅ,Bookcases & shelving units,910.0,No old price,True,https://www.ikea.com/sa/en/p/besta-tv-bench-wi...,Yes,"TV bench with doors, 120x42x7...",IKEA of Sweden,42.0,74.0,120.0

In [10]:
df_ikea.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3694 entries, 0 to 3693
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         3694 non-null   int64
 1   item_id            3694 non-null   int64
 2   name               3694 non-null   object
 3   category           3694 non-null   object
 4   price              3694 non-null   float64
 5   old_price          3694 non-null   object
 6   sellable_online    3694 non-null   bool
 7   link               3694 non-null   object
 8   other_colors       3694 non-null   object
 9   short_description  3694 non-null   object
 10  designer           3694 non-null   object
 11  depth              2231 non-null   float64
 12  height             2706 non-null   float64
 13  width              3105 non-null   float64
dtypes: bool(1), float64(4), int64(2), object(7)
memory usage: 378.9+ KB

In [11]:
df_ikea.describe()
'''
Також бачимо, що деякі поля в depth, height та width не заповнені, але це ок, бо не всі меблі мають такі параметри
Стовпець Unnamed: 0 нам не потрібен, бо вони дублюють порядкові номери строк

З опису видно, що середня ціна 1078, мінімальна 3, а максимальна 9585
Середня ширина виробів 54, мінімальна 1, а максимальна 257
Середня висота виробів 101.6, мінімальна 1, а максимальна 700
Середня довжина виробів 104.5, мінімальна 1, а максимальна 420
'''

,Unnamed: 0,item_id,price,depth,height,width
count,3694.000000,3.694000e+03,3694.000000,2231.000000,2706.000000,3105.000000
mean,1846.500000,4.863240e+07,1078.208419,54.379202,101.679970,104.470853
std,1066.510275,2.888709e+07,1374.652494,29.958351,61.097585,71.133771
min,0.000000,5.848700e+04,3.000000,1.000000,1.000000,1.000000
25%,923.250000,2.039057e+07,180.900000,38.000000,67.000000,60.000000
50%,1846.500000,4.928808e+07,544.700000,47.000000,83.000000,80.000000
75%,2769.750000,7.040357e+07,1429.500000,60.000000,124.000000,140.000000
max,3693.000000,9.993262e+07,9585.000000,257.000000,700.000000,420.000000

In [19]:
'''
Перевіримо на унікальність
Унікальних 2962 вироби з 3694
'''
df_ikea['item_id'].nunique()

2962

In [24]:
'''
Перевіримо чи не дублюються строки
Дублікатів не має, а повторюваність у item_id скоріше визвана зміною ціни або категорії
'''
df_ikea.duplicated(subset=['item_id', 'name']).sum()
df_ikea.duplicated(subset=['item_id', 'name', 'category', 'price', 'old_price']).sum()

732

In [ ]:
#Step2 - графіки